### ISSUE TITLE
how to use

### ISSUE THREAD

**Issue by DiskGetor** [drognisep/fynetree#5]
func main() {
	a := app.New()
	w := a.NewWindow("tree")
	setup()
	nodes := []*TreeNode{nodeA, nodeB, nodeC}
	for i, n := range nodes {
		fmt.Println("TestTreeNode_Append iteration", i)
		rootNode.Append(n)
		childLen := len(rootNode.children)
		println(childLen)
	}
	//how to SetContent with tree ?
	w.SetContent()//?
	rootNode.Append(nil)
	w.CenterOnScreen()
	w.ShowAndRun()
}

**Comment by drognisep** [comment]
Hi @DiskGetor,
There's an example on the develop branch.
https://github.com/drognisep/fynetree/tree/develop/example

Since fyne 1.4.0 is out (with 1.4.1 coming soon), I'll likely archive this in favor of their implementation. It still requires a model adapter layer like I use here for real world interactive trees, but it can be much simpler. I'm planning on writing up a blog post about it, and I'll post the link here when it's ready. :)

**Comment by DiskGetor** [comment]
> @DiskGetor，您好，
> develop分支上有一个示例。
> https://github.com/drognisep/fynetree/tree/develop/example
> 
> 由于fyne 1.4.0已经发布（即将推出1.4.1），因此我可能会将其归档以支持其实现。它仍然需要一个模型适配器层，就像我在这里用于现实世界的交互式树一样，但是它可以更加简单。我正计划撰写有关此主题的博客文章，并在准备好链接时将其发布在此处。:)

Thank you very much.

**Comment by DiskGetor** [comment]
> @DiskGetor，您好，
> develop分支上有一个示例。
> https://github.com/drognisep/fynetree/tree/develop/example
> 
> 由于fyne 1.4.0已经发布（即将推出1.4.1），因此我可能会将其归档以支持其实现。它仍然需要一个模型适配器层，就像我在这里用于现实世界的交互式树一样，但是它可以更加简单。我正计划撰写有关此主题的博客文章，并在准备好链接时将其发布在此处。:)

how to add widget.NewSeparator()  in func (renderer treeEntryRenderer) Layout(container fyne.Size) {

![image](https://user-images.githubusercontent.com/19886504/99554538-43bdb100-29fa-11eb-930f-907d45a5dde8.png)
![image](https://user-images.githubusercontent.com/19886504/99554594-546e2700-29fa-11eb-9821-d056a238f09a.png)

**Comment by drognisep** [comment]
Hi @DiskGetor!
I'm working on using the fyne tree widget in another project, and I've found that I need to essentially recreate fynetree to make it as interactive as I would like. So I tried using fynetree instead and was able to create an interactive tree much faster and easier.

If your use-case is purely as a display element, then I think the fyne widget will serve your purposes well since they have an easy to use string map based implementation. However, if you also need something more interactive, then fynetree may be a better fit for you. In light of this, I will **not** be archiving this repo, because I think the fyne tree has a long way to go to be as easy to setup or as interactive.

All in all, your mileage may vary, so I'm definitely open to feedback. To address the separators, I don't think that's really necessary or even helpful, and IMHO it clutters up the container quite a bit. Maybe your use requires it and I (and fynetree) could benefit from your insight?
